# -*- coding: utf-8 -*-
"""mario-agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buv7o0p09ycv4PHB5orHkZ21HgPS671i
"""

!pip install gym==0.21.0 -q
!pip install gym-super-mario-bros==7.4.0 -q
!pip install nes-py==8.2.1 -q
!pip install stable-baselines3[extra] -q
!pip install opencv-python -q

import pathlib, inspect

# Patch 1 — nes_py/_rom.py
import nes_py._rom as rom_module
rom_path = pathlib.Path(inspect.getfile(rom_module))
code = rom_path.read_text()
code = code.replace(
    'return self.prg_rom_start + self.prg_rom_size * 2**10',
    'return int(self.prg_rom_start) + int(self.prg_rom_size) * 1024'
)
code = code.replace(
    'return self.chr_rom_start + self.chr_rom_size * 2**10',
    'return int(self.chr_rom_start) + int(self.chr_rom_size) * 1024'
)
rom_path.write_text(code)
print("✅ Patch 1 nes_py/_rom.py OK")

# Patch 2 — gym_super_mario_bros/smb_env.py
import gym_super_mario_bros.smb_env as smb_module
smb_path = pathlib.Path(inspect.getfile(smb_module))
code = smb_path.read_text()
code = code.replace(
    'return self.ram[0x6d] * 0x100 + self.ram[0x86]',
    'return int(self.ram[0x6d]) * 0x100 + int(self.ram[0x86])'
)
smb_path.write_text(code)
print("✅ Patch 2 smb_env.py OK")

print("\n⚠️  Restart le runtime maintenant !")

import numpy as np
import gym
np.bool8 = np.bool_
np.float_ = np.float64

import cv2, collections, imageio
import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT
from nes_py.wrappers import JoypadSpace
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback
import gymnasium
from IPython.display import Image as IPImage, display
import torch

# ============ ENV ============
class MarioEnv(gymnasium.Env):
    metadata = {"render_modes": ["rgb_array"]}
    def __init__(self):
        self._env = gym_super_mario_bros.make('SuperMarioBros-v0')
        self._env = JoypadSpace(self._env, SIMPLE_MOVEMENT)
        self._skip = 4
        self._frames = collections.deque(maxlen=4)
        self.observation_space = gymnasium.spaces.Box(low=0, high=255, shape=(84, 84, 4), dtype=np.uint8)
        self.action_space = gymnasium.spaces.Discrete(self._env.action_space.n)

    def _preprocess(self, obs):
        gray = cv2.cvtColor(obs, cv2.COLOR_RGB2GRAY)
        return cv2.resize(gray, (84, 84), interpolation=cv2.INTER_AREA)

    def _get_obs(self):
        return np.stack(list(self._frames), axis=-1)

    def reset(self, seed=None, options=None):
        obs = self._env.reset()
        frame = self._preprocess(obs)
        for _ in range(4):
            self._frames.append(frame)
        return self._get_obs(), {}

    def step(self, action):
        action = int(np.asarray(action).flat[0])
        total_reward = 0.0
        terminated = False
        info = {}
        for _ in range(self._skip):
            obs, reward, done, info = self._env.step(action)
            total_reward += reward
            if done:
                terminated = True
                break
        self._frames.append(self._preprocess(obs))
        return self._get_obs(), float(np.sign(total_reward)), terminated, False, info

    def render(self):
        return self._env.render(mode='rgb_array')

    def close(self):
        self._env.close()

def make_mario_env(rank=0):
    def _init():
        env = MarioEnv()
        env = Monitor(env)
        return env
    return _init

print(" Wrappers OK")

# ============ ENTRAINEMENT ============
N_ENVS = 10

vec_env = DummyVecEnv([make_mario_env(i) for i in range(N_ENVS)])
vec_env = VecTransposeImage(vec_env)

eval_env = DummyVecEnv([make_mario_env(99)])
eval_env = VecTransposeImage(eval_env)

checkpoint_cb = CheckpointCallback(
    save_freq=50_000 // N_ENVS,
    save_path='./checkpoints/',
    name_prefix='mario_ppo'
)

eval_cb = EvalCallback(
    eval_env,
    eval_freq=50_000 // N_ENVS,
    best_model_save_path='./best_model/',
    n_eval_episodes=5,
    verbose=1
)

model = PPO(
    "CnnPolicy",
    vec_env,
    learning_rate=2.5e-4,
    n_steps=512,
    batch_size=64,
    n_epochs=4,
    gamma=0.99,
    gae_lambda=0.95,
    clip_range=0.2,
    ent_coef=0.01,
    verbose=1,
    tensorboard_log="./logs/",
    device="cuda" if torch.cuda.is_available() else "cpu"
)

model.learn(
    total_timesteps=500_000,
    callback=[checkpoint_cb, eval_cb],
    progress_bar=True
)

model.save("mario_ppo_500k")
print(" Training terminé !")

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import gym
np.bool8 = np.bool_
np.float_ = np.float64

import cv2, collections, imageio
import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT
from nes_py.wrappers import JoypadSpace
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage
from stable_baselines3.common.monitor import Monitor
import gymnasium
from IPython.display import Image as IPImage, display

# ============ ENV ============
class MarioEnv(gymnasium.Env):
    metadata = {"render_modes": ["rgb_array"]}
    def __init__(self):
        self._env = gym_super_mario_bros.make('SuperMarioBros-v0')
        self._env = JoypadSpace(self._env, SIMPLE_MOVEMENT)
        self._skip = 4
        self._frames = collections.deque(maxlen=4)
        self.observation_space = gymnasium.spaces.Box(low=0, high=255, shape=(84, 84, 4), dtype=np.uint8)
        self.action_space = gymnasium.spaces.Discrete(self._env.action_space.n)

    def _preprocess(self, obs):
        gray = cv2.cvtColor(obs, cv2.COLOR_RGB2GRAY)
        return cv2.resize(gray, (84, 84), interpolation=cv2.INTER_AREA)

    def _get_obs(self):
        return np.stack(list(self._frames), axis=-1)

    def reset(self, seed=None, options=None):
        obs = self._env.reset()
        frame = self._preprocess(obs)
        for _ in range(4):
            self._frames.append(frame)
        return self._get_obs(), {}

    def step(self, action):
        action = int(np.asarray(action).flat[0])
        total_reward = 0.0
        terminated = False
        info = {}
        for _ in range(self._skip):
            obs, reward, done, info = self._env.step(action)
            total_reward += reward
            if done:
                terminated = True
                break
        self._frames.append(self._preprocess(obs))
        return self._get_obs(), float(np.sign(total_reward)), terminated, False, info

    def render(self):
        return self._env.render(mode='rgb_array')

    def close(self):
        self._env.close()

def make_mario_env(rank=0):
    def _init():
        env = MarioEnv()
        env = Monitor(env)
        return env
    return _init

# ============ CHARGE MODELE ============
model = PPO.load("best_model/best_model")
print("Modele charge !")

env = DummyVecEnv([make_mario_env(0)])
env = VecTransposeImage(env)

# ============ 300 EPISODES ============
N_EPISODES = 300
best_frames = []
best_x = 0

print("Recherche du meilleur episode...")

for ep in range(N_EPISODES):
    obs = env.reset()
    done = [False]
    ep_frames = []
    ep_steps = 0

    while not done[0]:
        action, _ = model.predict(obs, deterministic=False)
        obs, reward, done, info = env.step(action)
        frame = env.envs[0].env._env.render(mode='rgb_array')
        frame_big = cv2.resize(
            frame,
            (frame.shape[1]*2, frame.shape[0]*2),
            interpolation=cv2.INTER_NEAREST
        )
        ep_frames.append(frame_big)
        ep_steps += 1
        if ep_steps >= 3000:
            break

    x_pos = info[0].get('x_pos', 0)
    score = info[0].get('score', 0)
    print(f"Episode {ep+1}/300 | X: {x_pos} | Score: {score} | Frames: {ep_steps}")

    if x_pos > best_x:
        best_x = x_pos
        best_frames = ep_frames.copy()
        print(f"  --> Nouveau meilleur ! X={best_x} score={score} 🎮")

print(f"\n✅ Meilleur episode : X={best_x}")
print(f"Total frames : {len(best_frames)}")

# ============ SAUVEGARDE GIF ============
print("Sauvegarde GIF...")
imageio.mimsave('mario_best.gif', best_frames[::2], duration=33)
print("✅ mario_best.gif sauvegarde !")

# ============ SAUVEGARDE MP4 ============
print("Sauvegarde MP4...")
h, w = best_frames[0].shape[:2]
out = cv2.VideoWriter(
    'mario_best.mp4',
    cv2.VideoWriter_fourcc(*'mp4v'),
    30,
    (w, h)
)
for f in best_frames:
    out.write(cv2.cvtColor(f, cv2.COLOR_RGB2BGR))
out.release()
print("✅ mario_best.mp4 sauvegarde !")

# ============ TELECHARGE LES FICHIERS ============
from google.colab import files
files.download('mario_best.gif')
files.download('mario_best.mp4')
print("✅ Fichiers telecharges !")

# ============ AFFICHE DANS COLAB ============
display(IPImage('mario_best.gif'))